//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_05_18_InventorySystem2.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }

        [Display (Name ="Employee Name")]
        [Required]
        public string EmployeeName { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string CellNo { get; set; }
        public string Address { get; set; }

        [Required]
        public Nullable<decimal> Salary { get; set; }

        public Nullable<int> UserId { get; set; }

        [Display (Name ="Available")]
        public string IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
