//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_05_18_InventorySystem2.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
        }
        
        public int SupplierId { get; set; }

        [Display (Name = "Supplier Name")]
        [Required]
        public string SupplierName { get; set; }

        [Display(Name = "Phone No")]
        [Required]
        public string CellNo { get; set; }

        [Required]
        public string Address { get; set; }

        [Display(Name ="Added By")]
        public string AddedBy { get; set; }

        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
