//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_05_18_InventorySystem2.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Employees = new HashSet<Employee>();
        }
        
        public int UserId { get; set; }

        [Required(AllowEmptyStrings =false,ErrorMessage ="Please Put user name")]
        [Display(Name ="User Name")]
        public string UserName { get; set; }

        [Required(AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name ="Role Name")]
        public string RoleName { get; set; }

        [Display(Name ="Added by")]
        public string AddedBy { get; set; }

        [Display(Name = "Available")]
        public string IsActive { get; set; }

            
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
